{"level":"ERROR","location":"[get_call:118] fyersModel","message":"Extra data: line 1 column 59 (char 58)","timestamp":"2023-08-20 08:58:03,585+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[get_call:118] fyersModel","message":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ANIFTY50-INDEX&resolution=15&date_format=0&range_from=1683863205&range_to=1692503205&cont_flag=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D0691FD4D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))","timestamp":"2023-08-20 09:16:55,984+0530","service":"FyersDataSocket"}
